### ISSUE TITLE
Binding stops working after some time

### ISSUE THREAD

**Issue by close2infinity** [andrasU/openhab-free-home-binding#10]
Hi, I have a F@H installation and installed the binding to my OpenHAB 3.3.0, running as a docker container. It works quite well, but after some hours, it simply stops doing anything - this happens _always_. As far as I can see, there isn't much in the logs indicating any problems (messages are the same when it's working), but I'm still quite new to OpenHAB so I may have missed something:

```
18:06:57.254 [INFO ] [openhab.event.ItemCommandEvent       ] - Item 'BeleuchtungAZFlo' received command 100
18:06:57.262 [INFO ] [openhab.event.ItemCommandEvent       ] - Item 'BeleuchtungAZFlo_DimmingValueChannel' received command 100
18:06:57.263 [INFO ] [openhab.event.ItemStatePredictedEvent] - Item 'BeleuchtungAZFlo_DimmingValueChannel' predicted to become 100`
```

Is this something that has been reported before? If not, do you have any idea what could be causing it?

**Comment by andrasU** [comment]
HI,
Thank you the interest
I did not see it, however due to other reasons I restart openhabian every night. Maybe this is not happening by me due to this restart.

At first I will switch the nightly restart off and see, what happens.

However you could activate the debug mode in the openhab console with the commend below to see more information from the binding.

`log:set DEBUG org.openhab.binding.freeathomesystem`

If you activated the debug mode and the problem is present again, please send me the log.

**Comment by close2infinity** [comment]
Hi, thanks for the quick response. Restarting the docker image on a daily basis was my idea, too, but it seems that the problem occurs after just some hours.

I set the log level to DEBUG, here is the interesting part:

```
13:59:31.363 [DEBUG] [ernal.handler.FreeAtHomeBridgeHandler] - Server connecting to websocket
13:59:31.365 [DEBUG] [mesystem.internal.handler.EventSocket] - Awaiting ending the communication from remote or error
13:59:31.365 [DEBUG] [mesystem.internal.handler.EventSocket] - Socket Error: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 429 Too Many Requests
```

**Comment by andrasU** [comment]
Thank you.. I will look for it.

**Comment by close2infinity** [comment]
I'm currently using version 3.3.0 of your binding. I'll try update to the most recent one and see if it goes away.

**Comment by close2infinity** [comment]
I'm happy to report that with the most recent version, the problem seems to be gone. Sorry, I didn't realize that I installed such an old version... anyway, thx or the support and, of course, for providing this binding in the first place!

**Comment by andrasU** [comment]
Hi @close2infinity,
I would like to ask you, which SysAP version are you using? Do you use already the 3.x.x or still the old 2.6.x?

Thank you

**Comment by close2infinity** [comment]
Hi, I'm still using 2.6.1. The stabel Update channel seems not to be offering anything more recent.
