### ISSUE TITLE
Malformed JSON

### ISSUE THREAD

**Issue by benjaminbinder82** [andrasU/openhab-free-home-binding#2]
After adding the bridge and trying to add a Thing e.g. a Thermostat i get the following error message

Status: 
UNINITIALIZED
HANDLER_INITIALIZING_ERROR
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $

I am using SysAP Firmware 2.6.1, the bridge is added successfully (shown as online in Openhab UI).

**Comment by andrasU** [comment]
The build from today is improved, that the setLenient(true) is added to the json handling. It must make a workaround in cases for malformed JSON. It would be great if you could have a look on the Current version. before you update to the new binding, please remove the old things, because a new property came to the things, which will be initialised only in the discovery.

Thank you

**Comment by benjaminbinder82** [comment]
Thanks for your reply. I installed the new version. I added the bridge (--> works) and a Thing Thermostat, which also works and shows "online" (before it showed above mentioned error). What is confusing now, I am not able to configure the channel in the UI, under configuration I have no fields to enter any information like the F@H channel ID and so on. Any advice on that?

**Comment by andrasU** [comment]
The binding is not need to configure the channel ID for free@home. it is automatically detected during discovery. Therefore the things shall not be added directly only via discovery. unfortunately I cannot hide the items in the list.

Therefore if you add the items via discovery the items will be configured properly. I attached you the picture:
![screen1](https://user-images.githubusercontent.com/47272385/107978875-d2bc7400-6fbd-11eb-8761-aae611f25c26.png)

After you properly added the channels are visible
![screen2](https://user-images.githubusercontent.com/47272385/107978911-e4058080-6fbd-11eb-85be-93e224e22c70.png)

Is it answering your question;
