### ISSUE TITLE
GET Request Storm / WS / Error 429 Too Many Requests

### ISSUE THREAD

**Issue by OlafSc** [andrasU/openhab-free-home-binding#8]
HI,

I had the Binding installed but not used (just the discovered Things, no Items). 

It created a massive amount of API traffic to the SysAP, to the point it blocked the OpenHAB server with "Error 429 Too many Requests". Something is broken... 

21:57:45.977284 IP OpenHabian.fritz.box.44610 > SysAP.fritz.box.http: Flags [P.], seq 15435:15750, ack 14701, win 501, options [nop,nop,TS val 1995117573 ecr 132889], length 315: HTTP: GET /fhapi/v1/api/ws HTTP/1.1
E..o..@.@.,..........B.P.7LK...............
v.......GET /fhapi/v1/api/ws HTTP/1.1
Accept-Encoding: gzip
User-Agent: Jetty/9.4.20.v20190813
Authorization: Basic 
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: 
Sec-WebSocket-Version: 13
Pragma: no-cache
Cache-Control: no-cache
Host: 192.168.2.11

21:57:45.977393 IP SysAP.fritz.box.http > OpenHabian.fritz.box.44558: Flags [P.], seq 18001:18301, ack 19215, win 1592, options [nop,nop,TS val 132889 ecr 1995117573], length 300: HTTP: HTTP/1.1 429 Too Many Requests
E..`..@.@..W.........P..S(.s..u....8.......
....v...HTTP/1.1 429 Too Many Requests
Server: 
Date: Tue, 16 Mar 2021 20:57:44 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 134
Connection: keep-alive

<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
</body>
</html>

21:57:45.977583 IP SysAP.fritz.box.http > OpenHabian.fritz.box.44610: Flags [P.], seq 14701:15001, ack 15750, win 1290, options [nop,nop,TS val 132889 ecr 1995117573], length 300: HTTP: HTTP/1.1 429 Too Many Requests
E..`..@.@../.........P.B.....7M....
.K.....
....v...HTTP/1.1 429 Too Many Requests
Server: 
Date: Tue, 16 Mar 2021 20:57:44 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 134
Connection: keep-alive

<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
</body>
</html>

21:57:45.978126 IP OpenHabian.fritz.box.44624 > SysAP.fritz.box.http: Flags [P.], seq 9135:9450, ack 8701, win 501, options [nop,nop,TS val 1995117574 ecr 132889], length 315: HTTP: GET /fhapi/v1/api/ws HTTP/1.1
E..o..@.@............P.P."k...<............
v.......GET /fhapi/v1/api/ws HTTP/1.1
Accept-Encoding: gzip
User-Agent: Jetty/9.4.20.v20190813
Authorization: Basic a
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: GPDw
Sec-WebSocket-Version: 13
Pragma: no-cache
Cache-Control: no-cache
Host: 192.168.2.11

21:57:45.978398 IP OpenHabian.fritz.box.44610 > SysAP.fritz.box.http: Flags [P.], seq 15750:16065, ack 15001, win 501, options [nop,nop,TS val 1995117574 ecr 132889], length 315: HTTP: GET /fhapi/v1/api/ws HTTP/1.1
E..o..@.@.,..........B.P.7M................
v.......GET /fhapi/v1/api/ws HTTP/1.1
Accept-Encoding: gzip
User-Agent: Jetty/9.4.20.v20190813
Authorization: Basic a
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: B
Sec-WebSocket-Version: 13
Pragma: no-cache
Cache-Control: no-cache
Host: 192.168.2.11

**Comment by andrasU** [comment]
Thank you the info, yesterday I recognised the same problem. The problem was present on may side if I had two different OpenHAB sessions to the same SysAP. But I will make some additional tests to find out the real root cause.

**Comment by jannodeluxe** [comment]
@andrasU is this issue already fixed? I was facing the same issues!

**Comment by andrasU** [comment]
I had some issues with the testing environment, and had to re-start the openhab every morning. The issue is coming only (at least in my environment) if the openhab is running more than one day.

The issue came again after the testing environment is fixed, I made a change to reduce the concurrent connections, and I start to test again

**Comment by jannodeluxe** [comment]
Hi Andras,

Hoffe dir geht es gut! Danke für die Rückmeldung. Kannst du mir sagen wann ich nochmal testen soll?
Ich habe dein Binding erstmal deaktiviert weil es sonst meinen SysAP API außer betrieb gesetzt hat mit der Meldung „too many requests“!

LG, Jan

**Comment by andrasU** [comment]
HI Jan,

Ich hoffe dass es auch dir in diesen CORONA-Zeiten gut geht. 

Ich suche seit paar Wochen diesen Fehler, was den SysAP lahm legt. Ich konnte aber effektiv in der letzten Zeit relativ wenig machen, weil ich trotz CORONA ziemlich viel Arbeit gehabt habe.
Bei mir kommt das Problem in der Regel von Abend auf Morgen, praktisch nach langem Idle-Zeit. 

Ich habe versucht die maximale Verbindungen zu begrenzen. Vor kurzem habe ich ziemlich viel Zustazdebug in der Binding reingestellt und lasse ich heute Nacht laufen, ich hoffe dass ich morgen oder vlt. am Samstag etwas im log habe.

Sobald ich etwas zum Testen habe melde ich mich.

Vielen Dank dir.

Gruß,

Andras

**Comment by jannodeluxe** [comment]
Hi Andras,

Hast du was Neues gefunden? Ich glaube ich habe einen Ansatzpunkt gefunden: Busch Jäger limitiert ja auf 20 Verbindungen pro Clienten. Wenn bei mir aber jetzt auf einem Gerät neben OpenHAB mit deinem Binding auch NodeRed hombridge und viele andere laufen dann bauen die alle eine Verbindung zum SysAP auf. Aber alle kommen Von der gleichen IP. Vllt sind dann die 20 Verbindungen schnell belegt. 
Wenn die Applikationen auf getrennten Geräten laufen würden hätten sie jeweils 20 Verbindungen am SysAP zur Verfügung.

Kann das setup und Problem bei dir auch deshalb kommen?

Dein Binding Schein bei mir sauber die Verbindugen auf und wieder abzubauen dh eine websocket Verbindung ist immer offen und die REST calls bauen auf und wieder ab.

LG Jan

**Comment by OlafSc** [comment]
Hi,

als ich das Problem hatte, zeigte ein TCPdump auf dem Interface massiven Verkehr des Bindings mit dem SysAP. 

Das sah schon eher nach irgendwas will zu viel Reden aus in dem Moment.

I

**Comment by andrasU** [comment]
Hi,

Ich suche immer noch das Problem. Manchmal läuft die Bindung tagelang, manchmal nur eine Nacht. Meine Beobachtung, dass Problem dann auftritt, wenn ich mit der neuen free@home App (Weiß/Hellblau) parallel auf den SysAp zugreife.

Die 20 parallele Verbindungen von einer IP sollen nicht mehr vorkommen, weil meine Binding die Verbindungen auf 1 eingeschränkt. Aber trotzdem kommt noch vor, dass der SysAp auf die Anfragen von Binding nach eine gewisse Zeit nicht mehr reagiert.

@OlafSc:
Eine Idee ist mir auf Grund der starken Netzwerkverkehr eingefallen. Es könnte sein, dass openHAB versuch eine Synchronisierung tun und dann fragt alle Items und Things ab. Diese Abfragen könnten aber sehr schnell (burst) passieren, was der SysAP als DoS Attack versteht und die Verbindung zum openHAB verweigert.

hast du das Problem mit dem starken Netzwerkverkehr in einem bestimmten Zeitpunkt gesehen? z.B.
* Nacht, wenn openHAB versucht z.B. die Items neu synchronisieren?
* welche items waren Teils diesem massieren Netzwerkverkehr, nur bestimmte?

Wenn man wüsste, was dieses Eine Idee ist mir auf Grund der starken Netzwerkverkehr eingefallen. Es könnte sein, dass openHAB versuch eine Synchronisierung tun und dann fragt alle Items und Things ab. Diese Abfragen könnten aber sehr schnell (burst) passieren, was der SysAP als DoS Attack versteht und die Verbindung zum openHAB verweigert.

so könnte man dieses Ereignis von openHAB noch 

ich frage nochmal die free@home support. Sie sind ziemlich hilfreich.

**Comment by OlafSc** [comment]
Hi - ich sah nur das nichts mehr ging und das der Sturm da war - das war Tags aber wann das anfing kann ich nicht sagen. Ich habe dann das Binding deinstalliert und das andere wieder in  Betrieb..

o

**Comment by jannodeluxe** [comment]
Hi @andrasU konntest du noch was rausfinden wegen den too many requests?

**Comment by andrasU** [comment]
Issue same as #10 and closed
